"""The web interface: pages to pick a layout and refresh the panel, to connect the
StudyLife account and to change the settings, from a phone on the same network. Standard
library only (`http.server`), inline CSS, no external resources.

Security model, in one paragraph: the person installing chooses DISPLAY_WEB_TOKEN; `serve`
refuses to start without one of at least MIN_TOKEN_LENGTH characters. The login form posts
the token, which is compared in constant time; a wrong one costs a second and a 403. A right
one sets an HttpOnly, SameSite=Strict session cookie whose value is an HMAC of the token
under a key drawn at process start, so cookies die with the process and the token itself is
never stored in the browser. State-changing POSTs additionally require a same-origin
`Sec-Fetch-Site` or `Origin`. The layout pages never call the StudyLife API: previews are
drawn from the cached payloads (or sample data), and a refresh runs the same pipeline the
five-minute timer uses, under the panel lock. The connect page is the one exception: it
redeems the consent assertion and asks `/api/auth/whoami` whose key it holds (see
`connect.py`); the key it obtains goes into a 0600 file for the root-only apply unit and
is never sent to the browser.

`GET /current.png` (cookie required) is the frame that is on the panel right now, as
`main._put_on_panel` kept it. `GET /healthz` is outside that model: no cookie, no
same-origin check, a JSON summary of the panel's state for an uptime monitor. It carries no
secret - never the token, never the cookie - and never calls the StudyLife API.
`GET /connect/callback` is the other route without a cookie: the browser arriving there
comes from StudyLife's redirect (which never carries a SameSite=Strict cookie); the
single-use state generated by an authenticated request is what binds it to this display.
"""

from __future__ import annotations

import hmac
import html
import io
import json
import logging
import secrets
import ssl
import threading
import time
from collections.abc import Callable
from datetime import datetime
from hashlib import sha256
from http import HTTPStatus
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlsplit

from pydantic import ValidationError

from studylife_display import package_version
from studylife_display.config import LANGUAGES, ROTATIONS, Settings, WebOverrides, parse_bind
from studylife_display.connect import (
    CLIENT_ID,
    ConnectError,
    PendingConnect,
    check_callback,
    exchange_assertion,
    loopback_redirect_uri,
    parse_callback,
    public_redirect_uri,
    root_is_overlay,
    setup_connect_url,
    start_connect,
    whoami,
    write_pending_credentials,
)
from studylife_display.current_frame import (
    DASHBOARD,
    CurrentFrame,
    load_current_frame,
    read_current_png,
)
from studylife_display.layouts import AUTO, LAYOUTS
from studylife_display.layouts.auto import (
    EXAM_SOON_DAYS,
    resolve_layout,
    rules_from_settings,
)
from studylife_display.layouts.common import TEXT
from studylife_display.model import DashboardData, build_dashboard
from studylife_display.quiet_hours import in_quiet_hours, quiet_hours_end
from studylife_display.render import render
from studylife_display.sample import sample_payloads
from studylife_display.settings_store import (
    effective_settings,
    is_valid_choice,
    load_layout_choice,
    override_sources,
    save_layout_choice,
    update_overrides,
    valid_choices,
)
from studylife_display.snapshot import load_snapshot
from studylife_display.status_store import REJECTED, load_status
from studylife_display.studylife_client import SCOPES
from studylife_display.times import zone
from studylife_display.update_check import fetch_latest_tag, is_newer, latest_release

log = logging.getLogger(__name__)

MIN_TOKEN_LENGTH = 12
SESSION_COOKIE = "studylife_display_session"
WRONG_TOKEN_DELAY_SECONDS = 1.0
MAX_BODY_BYTES = 64 * 1024
README_URL = "https://github.com/lukislp/studylife-display#readme"
README_OVERLAY_URL = "https://github.com/lukislp/studylife-display#sd-card-protection"
TIMER_UNIT = "studylife-display.timer"

# /healthz says "degraded" when the cached snapshot is older than this although the last
# fetch succeeded: three missed five-minute refreshes mean the timer is not running.
STALE_DEGRADED_MINUTES = 15

WEB_TEXT: dict[str, dict[str, str]] = {
    "de": {
        "title": "StudyLife Display",
        "login_heading": "Anmelden",
        "token_label": "Zugriffstoken",
        "login_button": "Anmelden",
        "wrong_token": "Falsches Zugriffstoken.",
        "forbidden": "Nicht erlaubt.",
        "not_found": "Nicht gefunden.",
        "bad_request": "Ungültige Anfrage.",
        "nav_layouts": "Layout",
        "nav_connect": "Verbinden",
        "nav_settings": "Einstellungen",
        "layouts_heading": "Layout",
        "apply": "Übernehmen",
        "refresh": "Jetzt aktualisieren",
        "auto_name": "Automatisch",
        "auto_description": "Wählt bei jeder Aktualisierung das passende Layout.",
        "auto_rules": (
            "Automatisch heißt, in dieser Reihenfolge: Wochenrückblick im Fenster {review}; "
            "Prüfung, wenn die nächste Prüfung in höchstens {days} Tagen ansteht; Fokus, solange "
            "ein Timer läuft; Tagesplan, solange heute noch eine Session bevorsteht, im Fenster "
            "{agenda}; sonst Klassisch. Semester wird nie automatisch gewählt."
        ),
        "auto_off": "aus",
        "sessions_failed": (
            "Die Sessions für den Tagesplan konnten nicht geladen werden ({message}). Ein vor "
            "dem Scope Sessions.GetAll ausgestellter Schlüssel muss neu ausgestellt werden; "
            "die anderen Layouts sind nicht betroffen."
        ),
        "auto_now": "derzeit: {layout}",
        "last_updated": "Panel zuletzt aktualisiert: {time}",
        "never_updated": "Panel noch nie aktualisiert (kein Zwischenspeicher).",
        "current_heading": "Aktuell auf dem Panel",
        "current_line": "Gezeigt seit {time} · {what}",
        "current_none": "Noch kein Bild auf dem Panel gezeigt.",
        "current_kind_error": "Fehlerbildschirm",
        "current_kind_setup": "Einrichtungsbildschirm",
        "current_alt": "Das Bild, das gerade auf dem Panel zu sehen ist",
        "setup_hint": "Noch kein Schlüssel hinterlegt – Konto verbinden unter: {url}",
        "sample_note": (
            "Die Vorschauen zeigen Beispieldaten, weil noch kein Zwischenspeicher vorhanden ist."
        ),
        "full_refresh_note": "Ein Layoutwechsel ist eine vollständige Aktualisierung des Panels.",
        "flash_saved": "Layout gespeichert und Panel aktualisiert.",
        "flash_refreshed": "Panel aktualisiert.",
        "flash_failed": "Aktualisierung fehlgeschlagen, siehe Protokoll.",
        "flash_busy": "Das Panel ist gerade beschäftigt, bitte gleich noch einmal versuchen.",
        "logout": "Abmelden",
        "quiet_until": "Ruhezeit bis {time} – der Zeitplan pausiert, die Knöpfe hier nicht.",
        "last_error": "Letzter Fehler ({time}): {message}",
        "version": "Version {version}",
        "update_available": "Neue Version verfügbar: {tag}",
        # -- connect page
        "connect_heading": "Verbinden",
        "connect_intro": (
            "Verbindet dieses Display mit deinem StudyLife-Konto auf {instance}, ohne einen "
            "Schlüssel abzutippen. Der Client „{client}“ muss auf der Instanz registriert sein, "
            "mit den Scopes {scopes} und der Redirect-URI {redirect_uri} (siehe README)."
        ),
        "connect_no_key": "Noch kein Schlüssel hinterlegt.",
        "connect_connected": (
            "Verbunden mit {instance} · Benutzer-ID {user_id} · Anmeldung: {credential}"
        ),
        "connect_rejected": "{instance} lehnt den hinterlegten Schlüssel ab ({detail}).",
        "connect_unreachable": "{instance} ist nicht erreichbar ({detail}).",
        "connect_overlay": (
            "Das Root-Dateisystem ist ein Overlay: ein jetzt übernommener Schlüssel gilt nur bis "
            "zum nächsten Neustart. Erst verbinden, dann das Overlay einschalten – siehe README, "
            "Abschnitt SD-Karten-Schutz."
        ),
        "connect_start": "Verbindung starten",
        "connect_restart": "Neuen Link erzeugen",
        "connect_valid_until": "Link gültig bis {time}.",
        "connect_step_open": (
            "1. Diesen Link auf einem beliebigen Gerät öffnen, in StudyLife anmelden und die "
            "Verbindung bestätigen:"
        ),
        "connect_step_paste": (
            "2. Der Browser landet danach auf einer Adresse, die mit {redirect_uri} beginnt und "
            "sich nicht laden lässt – das ist so gedacht. Die ganze Adresse aus der "
            "Adresszeile kopieren und hier einfügen:"
        ),
        "connect_step_redirect": (
            "2. Nach der Bestätigung kehrt der Browser von selbst hierher zurück ({redirect_uri})."
        ),
        "connect_paste_label": "Adresse aus der Adresszeile",
        "connect_paste_button": "Schlüssel abholen",
        "connect_flash_started": "Link erzeugt.",
        "connect_flash_applied": (
            "Schlüssel übernommen, Dienst startet neu – danach bitte erneut anmelden."
        ),
        "connect_flash_no_pending": "Kein laufender Verbindungsversuch – bitte neu starten.",
        "connect_flash_expired": "Der Link ist abgelaufen – bitte einen neuen erzeugen.",
        "connect_flash_state_mismatch": (
            "Die eingefügte Adresse gehört nicht zu diesem Verbindungsversuch."
        ),
        "connect_flash_missing_assertion": (
            "In der eingefügten Adresse fehlt die Bestätigung (assertion=…)."
        ),
        "connect_flash_exchange_rejected": (
            "StudyLife hat die Bestätigung nicht angenommen – sie ist verbraucht oder abgelaufen."
        ),
        "connect_flash_exchange_failed": "StudyLife hat die Verbindung abgelehnt ({detail}).",
        "connect_flash_unreachable": "StudyLife ist nicht erreichbar ({detail}).",
        "connect_flash_write_failed": "Der Schlüssel konnte nicht abgelegt werden ({detail}).",
        "connect_callback_done": (
            "Schlüssel übernommen, Dienst startet neu. Dieses Fenster kann geschlossen werden."
        ),
        # -- settings page
        "settings_heading": "Einstellungen",
        "settings_intro": (
            "Hier gespeicherte Werte gelten vor den Umgebungsvariablen und überstehen einen "
            "Neustart wie die Layoutwahl."
        ),
        "settings_language": "Sprache",
        "settings_rotate": "Drehung",
        "settings_rotate_0": "0° (aufrecht)",
        "settings_rotate_180": "180° (kopfüber montiert)",
        "settings_quiet_hours": "Ruhezeit",
        "settings_quiet_hours_hint": (
            "HH-HH oder HH:MM-HH:MM, darf über Mitternacht gehen; leer = aus."
        ),
        "settings_clear_at": "Tägliche Reinigung um",
        "settings_clear_at_hint": "HH:MM; leer = aus.",
        "settings_auto_review": "Automatik: Wochenrückblick im Fenster",
        "settings_auto_review_hint": (
            "[Wochentage] HH-HH oder HH:MM-HH:MM, z. B. „sun 18-24“ (24 = Mitternacht, kein "
            "Übergang über Mitternacht); leer = Regel aus."
        ),
        "settings_auto_agenda": "Automatik: Tagesplan im Fenster",
        "settings_auto_agenda_hint": (
            "HH-HH oder HH:MM-HH:MM, z. B. „06-12“, optional mit Wochentagen davor; leer = "
            "Regel aus."
        ),
        "settings_update_check": "Auf neue Version prüfen (fragt GitHub, alle 6 h)",
        "settings_source_file": "aus settings.json",
        "settings_source_env": "aus Umgebung/Standard",
        "settings_save": "Speichern",
        "settings_reset": "Auf Umgebungswerte zurücksetzen",
        "settings_flash_saved": "Einstellungen gespeichert.",
        "settings_flash_reset": "Einstellungen zurückgesetzt, es gelten die Umgebungswerte.",
        "settings_invalid": "Bitte die markierten Felder korrigieren.",
        "settings_readonly_heading": "Nur in der Umgebung",
        "settings_readonly_note": (
            "Diese Werte kommen aus /etc/studylife-display.env und lassen sich hier nicht ändern."
        ),
        "settings_interval": "Aktualisierungsintervall",
        "settings_interval_value": (
            "durch den systemd-Timer {unit} festgelegt (Standard: alle 5 Minuten)"
        ),
        "settings_set": "gesetzt",
        "settings_unset": "nicht gesetzt",
        "settings_env_source": "Umgebung",
    },
    "en": {
        "title": "StudyLife Display",
        "login_heading": "Sign in",
        "token_label": "Access token",
        "login_button": "Sign in",
        "wrong_token": "Wrong access token.",
        "forbidden": "Not allowed.",
        "not_found": "Not found.",
        "bad_request": "Bad request.",
        "nav_layouts": "Layout",
        "nav_connect": "Connect",
        "nav_settings": "Settings",
        "layouts_heading": "Layout",
        "apply": "Apply",
        "refresh": "Refresh now",
        "auto_name": "Automatic",
        "auto_description": "Picks the fitting layout on every refresh.",
        "auto_rules": (
            "Automatic means, in this order: weekly review inside the window {review}; exam "
            "when the next exam is at most {days} days away; focus while a timer runs; agenda "
            "while a session planned for today still lies ahead, inside the window {agenda}; "
            "otherwise classic. Semester is never picked automatically."
        ),
        "auto_off": "off",
        "sessions_failed": (
            "The sessions for the agenda could not be fetched ({message}). A key issued before "
            "the Sessions.GetAll scope existed has to be re-issued; the other layouts are not "
            "affected."
        ),
        "auto_now": "currently: {layout}",
        "last_updated": "Panel last updated: {time}",
        "never_updated": "Panel never updated yet (no cache).",
        "current_heading": "Currently on the panel",
        "current_line": "Shown since {time} · {what}",
        "current_none": "Nothing has been shown on the panel yet.",
        "current_kind_error": "error screen",
        "current_kind_setup": "setup screen",
        "current_alt": "The picture that is on the panel right now",
        "setup_hint": "No key stored yet – connect your account at: {url}",
        "sample_note": "The previews show sample data because there is no cache yet.",
        "full_refresh_note": "Switching layouts is a full refresh of the panel.",
        "flash_saved": "Layout saved and panel refreshed.",
        "flash_refreshed": "Panel refreshed.",
        "flash_failed": "Refresh failed, see the log.",
        "flash_busy": "The panel is busy right now, please try again in a moment.",
        "logout": "Sign out",
        "quiet_until": "Quiet until {time} – the schedule pauses, the buttons here do not.",
        "last_error": "Last error ({time}): {message}",
        "version": "Version {version}",
        "update_available": "Update available: {tag}",
        # -- connect page
        "connect_heading": "Connect",
        "connect_intro": (
            "Connects this display to your StudyLife account on {instance} without copying a "
            "key. The client “{client}” has to be registered on the instance with the scopes "
            "{scopes} and the redirect URI {redirect_uri} (see the README)."
        ),
        "connect_no_key": "No key stored yet.",
        "connect_connected": (
            "Connected to {instance} · user ID {user_id} · credential: {credential}"
        ),
        "connect_rejected": "{instance} rejects the stored key ({detail}).",
        "connect_unreachable": "{instance} is unreachable ({detail}).",
        "connect_overlay": (
            "The root filesystem is an overlay: a key applied now holds only until the next "
            "reboot. Connect first, then enable the overlay – see the README, section SD-card "
            "protection."
        ),
        "connect_start": "Start connecting",
        "connect_restart": "Generate a new link",
        "connect_valid_until": "Link valid until {time}.",
        "connect_step_open": (
            "1. Open this link on any device, sign in to StudyLife and approve the connection:"
        ),
        "connect_step_paste": (
            "2. The browser then lands on an address starting with {redirect_uri} that it cannot "
            "load – that is expected. Copy the whole address from the address bar and paste it "
            "here:"
        ),
        "connect_step_redirect": (
            "2. After approving, the browser returns here on its own ({redirect_uri})."
        ),
        "connect_paste_label": "Address from the address bar",
        "connect_paste_button": "Fetch the key",
        "connect_flash_started": "Link generated.",
        "connect_flash_applied": "Key applied, the service is restarting – please sign in again.",
        "connect_flash_no_pending": "No connection attempt in progress – please start again.",
        "connect_flash_expired": "The link has expired – please generate a new one.",
        "connect_flash_state_mismatch": "The pasted address does not belong to this attempt.",
        "connect_flash_missing_assertion": "The pasted address carries no approval (assertion=…).",
        "connect_flash_exchange_rejected": (
            "StudyLife did not accept the approval – it was used already or has expired."
        ),
        "connect_flash_exchange_failed": "StudyLife refused the connection ({detail}).",
        "connect_flash_unreachable": "StudyLife is unreachable ({detail}).",
        "connect_flash_write_failed": "The key could not be stored ({detail}).",
        "connect_callback_done": (
            "Key applied, the service is restarting. You can close this window."
        ),
        # -- settings page
        "settings_heading": "Settings",
        "settings_intro": (
            "Values saved here take precedence over the environment variables and survive a "
            "reboot like the layout choice."
        ),
        "settings_language": "Language",
        "settings_rotate": "Rotation",
        "settings_rotate_0": "0° (upright)",
        "settings_rotate_180": "180° (mounted upside down)",
        "settings_quiet_hours": "Quiet hours",
        "settings_quiet_hours_hint": "HH-HH or HH:MM-HH:MM, may wrap past midnight; empty = off.",
        "settings_clear_at": "Daily clear at",
        "settings_clear_at_hint": "HH:MM; empty = off.",
        "settings_auto_review": "Auto: weekly review inside the window",
        "settings_auto_review_hint": (
            "[weekdays] HH-HH or HH:MM-HH:MM, e.g. “sun 18-24” (24 = midnight, no wrap past "
            "midnight); empty = rule off."
        ),
        "settings_auto_agenda": "Auto: agenda inside the window",
        "settings_auto_agenda_hint": (
            "HH-HH or HH:MM-HH:MM, e.g. “06-12”, optionally with weekdays in front; empty = "
            "rule off."
        ),
        "settings_update_check": "Check for a newer release (asks GitHub every 6 h)",
        "settings_source_file": "from settings.json",
        "settings_source_env": "from environment/default",
        "settings_save": "Save",
        "settings_reset": "Reset to the environment values",
        "settings_flash_saved": "Settings saved.",
        "settings_flash_reset": "Settings reset, the environment values apply.",
        "settings_invalid": "Please correct the marked fields.",
        "settings_readonly_heading": "Environment only",
        "settings_readonly_note": (
            "These values come from /etc/studylife-display.env and cannot be changed here."
        ),
        "settings_interval": "Refresh interval",
        "settings_interval_value": "set by the systemd timer {unit} (default: every 5 minutes)",
        "settings_set": "set",
        "settings_unset": "not set",
        "settings_env_source": "environment",
    },
}

FLASH_KEYS = {"saved", "refreshed", "failed", "busy"}
CONNECT_FLASH_KEYS = {
    "started",
    "applied",
    "no_pending",
    "expired",
    "state_mismatch",
    "missing_assertion",
    "exchange_rejected",
    "exchange_failed",
    "unreachable",
    "write_failed",
}
SETTINGS_FLASH_KEYS = {"saved", "reset"}

# The environment-only values the settings page lists, and whether their value is shown
# (a secret is only ever "set"/"not set").
READONLY_FIELDS: tuple[tuple[str, str, bool], ...] = (
    ("STUDYLIFE_BASE_URL", "studylife_base_url", True),
    ("STUDYLIFE_API_KEY", "studylife_api_key", False),
    ("STUDYLIFE_TIMEZONE", "studylife_timezone", True),
    ("DISPLAY_DRIVER", "display_driver", True),
    ("DISPLAY_STATE_PATH", "display_state_path", True),
    ("DISPLAY_PERSIST_PATH", "display_persist_path", True),
    ("DISPLAY_STALE_ERROR_HOURS", "display_stale_error_hours", True),
    ("DISPLAY_WEB_BIND", "display_web_bind", True),
    ("DISPLAY_WEB_TOKEN", "display_web_token", False),
    ("DISPLAY_PUBLIC_BASE_URL", "display_public_base_url", True),
    ("DISPLAY_SETUP_URL", "display_setup_url", True),
)

STYLE = """
:root { color-scheme: light dark; }
body { font-family: system-ui, sans-serif; margin: 0; padding: 16px; max-width: 1100px;
  margin-inline: auto; line-height: 1.4; }
h1 { font-size: 1.4rem; margin: 0 0 12px; }
h2 { font-size: 1.1rem; margin: 24px 0 8px; }
nav { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 16px; font-size: .95rem; }
nav a[aria-current] { font-weight: 600; text-decoration: none; }
nav form { display: inline; }
nav button { padding: 0; border: 0; background: none; color: inherit; text-decoration: underline;
  cursor: pointer; font: inherit; }
p.note { opacity: .8; font-size: .95rem; }
p.flash { border: 1px solid currentColor; border-radius: 8px; padding: 8px 12px; }
p.warn { border: 2px solid currentColor; border-radius: 8px; padding: 8px 12px; font-weight: 600; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 16px; margin: 16px 0; }
.card { border: 1px solid #8884; border-radius: 12px; padding: 12px; display: block; }
.card img { width: 100%; height: auto; border: 1px solid #8886; background: #fff;
  border-radius: 4px; }
.current { max-width: 560px; margin: 8px 0 16px; }
.current img { width: 100%; height: auto; border: 1px solid #8886; background: #fff;
  border-radius: 4px; display: block; }
.card b { font-size: 1.05rem; }
.card small { display: block; opacity: .8; margin: 4px 0 8px; }
.actions { display: flex; gap: 12px; flex-wrap: wrap; align-items: center; }
button { font: inherit; padding: 10px 18px; border-radius: 8px; border: 1px solid #8888;
  cursor: pointer; }
button.primary { font-weight: 600; }
form.login { max-width: 360px; }
footer { margin-top: 24px; opacity: .7; font-size: .9rem; }
input[type=password], input[type=text], select, textarea { font: inherit; width: 100%;
  box-sizing: border-box; padding: 10px; border-radius: 8px; border: 1px solid #8888;
  margin: 6px 0 12px; }
textarea { min-height: 96px; font-family: ui-monospace, monospace; font-size: .9rem; }
.field { max-width: 560px; }
.field small { display: block; opacity: .8; margin: -8px 0 12px; }
.field .error { color: #c62828; font-weight: 600; opacity: 1; }
.field .source { opacity: .7; font-size: .85rem; margin-left: 8px; font-weight: normal; }
pre.link { white-space: pre-wrap; word-break: break-all; border: 1px solid #8886;
  border-radius: 8px; padding: 10px; font-size: .85rem; }
table { border-collapse: collapse; width: 100%; max-width: 760px; font-size: .95rem; }
td, th { text-align: left; padding: 6px 8px; border-bottom: 1px solid #8884; vertical-align: top; }
td.mono { font-family: ui-monospace, monospace; word-break: break-all; }
"""


def health_report(settings: Settings, now: datetime) -> tuple[dict[str, Any], HTTPStatus]:
    """The JSON for /healthz and its HTTP status: "setup" (200) while no API key is
    configured at all (the panel shows the setup screen; `setup` is true), "ok" (200) when
    the last fetch succeeded and the snapshot is fresh, "degraded" (200) when the last fetch
    failed but a cached dashboard is shown or the snapshot is older than
    STALE_DEGRADED_MINUTES outside quiet hours, "error" (503) when the key was rejected or
    there is no data at all."""
    settings = effective_settings(settings)
    setup = not settings.studylife_api_key
    tz = zone(settings.studylife_timezone)
    state_path = Path(settings.display_state_path)
    status = load_status(state_path.parent, tz)
    snapshot = load_snapshot(state_path, tz)
    quiet = in_quiet_hours(now, settings.display_quiet_hours)

    layout: str | None = None
    stale_minutes: int | None = None
    last_fetch_at = status.last_fetch_at
    if snapshot is not None:
        data = build_dashboard(
            snapshot.metrics,
            snapshot.history,
            snapshot.timer,
            now,
            tz,
            snapshot.fetched_at,
            sessions=snapshot.sessions,
        )
        layout = resolve_layout(load_layout_choice(settings), data, rules_from_settings(settings))
        stale_minutes = data.stale_minutes
        if last_fetch_at is None:
            last_fetch_at = snapshot.fetched_at

    error = status.last_error
    rejected = error is not None and error.kind == REJECTED and not status.last_fetch_ok
    timer_silent = (
        stale_minutes is not None and stale_minutes > STALE_DEGRADED_MINUTES and not quiet
    )
    if setup:
        state = "setup"
    elif rejected or snapshot is None:
        state = "error"
    elif not status.last_fetch_ok or timer_silent:
        state = "degraded"
    else:
        state = "ok"

    report: dict[str, Any] = {
        "status": state,
        "setup": setup,
        "version": package_version(),
        "last_fetch_at": None if last_fetch_at is None else last_fetch_at.isoformat(),
        "last_fetch_ok": status.last_fetch_ok,
        "stale_minutes": stale_minutes,
        "last_error": None if error is None else error.as_json(),
        "last_panel_update_at": (
            None if status.last_panel_update_at is None else status.last_panel_update_at.isoformat()
        ),
        "layout": layout,
        "quiet_hours_active": quiet,
        "sessions_ok": status.sessions_ok,
    }
    return report, HTTPStatus.OK if state != "error" else HTTPStatus.SERVICE_UNAVAILABLE


def _page(title: str, body: str) -> bytes:
    document = (
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>{html.escape(title)}</title><style>{STYLE}</style></head>"
        f"<body>{body}</body></html>"
    )
    return document.encode("utf-8")


class WebApp:
    """Everything the request handler needs that is not the request itself."""

    def __init__(self, settings: Settings, refresh: Callable[[], int]) -> None:
        # The environment settings; what the pages show and act on is `effective()`,
        # re-read per request so a change on the settings page applies right away.
        self.settings = settings
        self.refresh = refresh
        # A fresh key per process: sessions are worthless after a restart, and the token
        # itself never leaves the environment file.
        self._session_value = hmac.new(
            secrets.token_bytes(32), settings.display_web_token.encode("utf-8"), sha256
        ).hexdigest()
        # The one connection attempt in progress, if any; memory only, single-use.
        self._pending: PendingConnect | None = None
        self._pending_lock = threading.Lock()
        # Detail of the last connect failure, for the flash message after the redirect.
        self._flash_detail = ""

    def effective(self) -> Settings:
        return effective_settings(self.settings)

    @property
    def language(self) -> str:
        return self.effective().display_language

    @property
    def text(self) -> dict[str, str]:
        return WEB_TEXT[self.language]

    @property
    def state_dir(self) -> Path:
        return Path(self.settings.display_state_path).parent

    def now(self) -> datetime:
        return datetime.now(zone(self.settings.studylife_timezone))

    # -- authentication -----------------------------------------------------------------

    def token_matches(self, candidate: str) -> bool:
        return hmac.compare_digest(
            candidate.encode("utf-8"), self.settings.display_web_token.encode("utf-8")
        )

    def session_cookie_value(self) -> str:
        return self._session_value

    def is_authenticated(self, cookie_header: str | None) -> bool:
        if not cookie_header:
            return False
        jar: SimpleCookie = SimpleCookie()
        try:
            jar.load(cookie_header)
        except Exception:
            return False
        morsel = jar.get(SESSION_COOKIE)
        return morsel is not None and hmac.compare_digest(morsel.value, self._session_value)

    # -- data ---------------------------------------------------------------------------

    def current_data(self) -> tuple[DashboardData, bool]:
        """The dashboard as the panel would draw it right now, from the cache; sample data
        (flagged True) when there is no cache. Never touches the API."""
        tz = zone(self.settings.studylife_timezone)
        now = datetime.now(tz)
        snapshot = load_snapshot(Path(self.settings.display_state_path), tz)
        if snapshot is None:
            metrics, history, timer, sessions = sample_payloads(now, tz)
            return build_dashboard(metrics, history, timer, now, tz, sessions=sessions), True
        data = build_dashboard(
            snapshot.metrics,
            snapshot.history,
            snapshot.timer,
            now,
            tz,
            snapshot.fetched_at,
            sessions=snapshot.sessions,
        )
        return data, False

    def preview_png(self, key: str) -> bytes:
        data, _ = self.current_data()
        layout = resolve_layout(key, data, rules_from_settings(self.effective()))
        image = render(data, self.language, layout)
        buffer = io.BytesIO()
        image.save(buffer, format="PNG")
        return buffer.getvalue()

    def current_frame(self) -> CurrentFrame | None:
        """What is on the panel right now, or None before the first frame."""
        return load_current_frame(self.state_dir, zone(self.settings.studylife_timezone))

    def current_png(self) -> bytes | None:
        return read_current_png(self.state_dir)

    def current_block(self) -> str:
        """The "currently on the panel" section of the layouts page: the picture with when
        it was shown and what it is, or one plain line while nothing was shown yet."""
        t = self.text
        parts = [f"<h2>{html.escape(t['current_heading'])}</h2>"]
        frame = self.current_frame()
        if frame is None:
            parts.append(f"<p class='note'>{html.escape(t['current_none'])}</p>")
            return "".join(parts)
        language = self.language
        if frame.kind == DASHBOARD and frame.layout in LAYOUTS:
            what = LAYOUTS[frame.layout].name[language]
        elif frame.kind == DASHBOARD:
            what = frame.layout or ""
        else:
            what = t["current_kind_" + frame.kind]
        stamp = frame.shown_at.strftime(TEXT[language]["date_format"] + " %H:%M")
        line = t["current_line"].format(time=stamp, what=what)
        parts.append(
            "<div class='current'>"
            f"<img src='/current.png?t={int(frame.shown_at.timestamp())}' width='800' "
            f"height='480' alt='{html.escape(t['current_alt'], quote=True)}'>"
            f"<p class='note'>{html.escape(line)}</p></div>"
        )
        return "".join(parts)

    def setup_hint(self) -> str:
        """The "connect at ..." line the layouts page shows while no key is stored; empty
        once there is one."""
        if self.settings.studylife_api_key:
            return ""
        url = setup_connect_url(self.settings)
        text = self.text["setup_hint"].format(url=url)
        before, _, _ = text.partition(url)
        return (
            f"<p class='warn'>{html.escape(before)}"
            f"<a href='{html.escape(url, quote=True)}'>{html.escape(url)}</a></p>"
        )

    # -- connecting ---------------------------------------------------------------------

    def connect_mode(self) -> tuple[str, str]:
        """("redirect", uri) with DISPLAY_PUBLIC_BASE_URL, ("paste", uri) otherwise."""
        public = self.settings.display_public_base_url
        if public:
            return "redirect", public_redirect_uri(public)
        return "paste", loopback_redirect_uri(parse_bind(self.settings.display_web_bind)[1])

    def pending(self) -> PendingConnect | None:
        """The attempt in progress, or None once it has expired."""
        with self._pending_lock:
            pending = self._pending
            if pending is not None and pending.expired(self.now()):
                self._pending = None
                return None
            return pending

    def begin_connect(self) -> PendingConnect:
        _, redirect_uri = self.connect_mode()
        pending = start_connect(str(self.settings.studylife_base_url), redirect_uri, self.now())
        with self._pending_lock:
            self._pending = pending
        log.info("connect attempt started (redirect_uri=%s)", redirect_uri)
        return pending

    def finish_connect(self, text: str) -> str:
        """Checks the callback (pasted or received), redeems the assertion and drops the
        key into the pending file. Returns the flash key; the attempt is consumed on any
        outcome but a missing assertion, so a URL cannot be tried twice."""
        try:
            result = parse_callback(text)
        except ConnectError as exc:
            return exc.key
        with self._pending_lock:
            pending = self._pending
            self._pending = None
        try:
            check_callback(pending, result, self.now())
            assert pending is not None
            api_key, user_id = exchange_assertion(
                str(self.settings.studylife_base_url), CLIENT_ID, result.assertion, pending.verifier
            )
        except ConnectError as exc:
            log.warning("connect attempt failed: %s", exc)
            self._flash_detail = exc.detail
            return exc.key
        try:
            write_pending_credentials(
                self.state_dir, api_key, str(self.settings.studylife_base_url), self.now()
            )
        except OSError as exc:
            log.error("could not write the pending credentials: %s", exc)
            self._flash_detail = str(exc)
            return "write_failed"
        log.info("API key obtained for user %s, handed to credentials-apply", user_id)
        return "applied"

    def identity_line(self) -> str:
        """What the connect page says about the stored key: nothing stored, or whoami's
        answer, or why it could not be obtained."""
        t = self.text
        instance = str(self.settings.studylife_base_url).rstrip("/")
        key = self.settings.studylife_api_key
        if not key:
            return t["connect_no_key"]
        try:
            who = whoami(instance, key, self.settings.http_timeout_seconds)
        except ConnectError as exc:
            template = t["connect_rejected"] if exc.key == "rejected" else t["connect_unreachable"]
            return template.format(instance=instance, detail=exc.detail)
        return t["connect_connected"].format(
            instance=instance, user_id=who.get("userId"), credential=who.get("credential")
        )

    # -- settings -----------------------------------------------------------------------

    def parse_settings_form(self, form: dict[str, str]) -> tuple[dict[str, Any], dict[str, str]]:
        """(values, errors): the submitted values converted to the settings.json types and,
        per field, the validation message from WebOverrides - the same rules as the
        environment. An unparsable rotation is an error too."""
        values: dict[str, Any] = {
            "language": form.get("language", ""),
            "quiet_hours": form.get("quiet_hours", ""),
            "clear_at": form.get("clear_at", ""),
            "update_check": form.get("update_check") == "on",
            "auto_review": form.get("auto_review", ""),
            "auto_agenda": form.get("auto_agenda", ""),
        }
        errors: dict[str, str] = {}
        rotate_raw = form.get("rotate", "").strip()
        try:
            values["rotate"] = int(rotate_raw)
        except ValueError:
            errors["rotate"] = f"must be one of {ROTATIONS}, not {rotate_raw!r}"
        for key, value in values.items():
            try:
                WebOverrides.model_validate({key: value})
            except ValidationError as exc:
                errors[key] = exc.errors()[0]["msg"].removeprefix("Value error, ")
        return values, errors

    # -- pages --------------------------------------------------------------------------

    def _nav(self, current: str) -> str:
        t = self.text
        links = [("/", "nav_layouts"), ("/connect", "nav_connect"), ("/settings", "nav_settings")]
        parts = ["<nav>"]
        for href, key in links:
            marker = " aria-current='page'" if href == current else ""
            parts.append(f"<a href='{href}'{marker}>{html.escape(t[key])}</a>")
        parts.append(
            "<form method='post' action='/logout'>"
            f"<button type='submit'>{html.escape(t['logout'])}</button></form></nav>"
        )
        return "".join(parts)

    def login_page(self, error: str | None = None) -> bytes:
        t = self.text
        message = f"<p class='flash'>{html.escape(error)}</p>" if error else ""
        body = (
            f"<h1>{html.escape(t['title'])}</h1>{message}"
            f"<form class='login' method='post' action='/login'>"
            f"<label for='token'>{html.escape(t['token_label'])}</label>"
            "<input id='token' name='token' type='password' autocomplete='current-password' "
            "autofocus required>"
            f"<button class='primary' type='submit'>{html.escape(t['login_button'])}</button>"
            "</form>"
        )
        return _page(t["title"], body)

    def layouts_page(self, flash: str | None = None) -> bytes:
        t = self.text
        settings = self.effective()
        language = self.language
        data, is_sample = self.current_data()
        choice = load_layout_choice(settings)
        resolved = resolve_layout(AUTO, data, rules_from_settings(settings))
        parts = [f"<h1>{html.escape(t['title'])} · {html.escape(t['layouts_heading'])}</h1>"]
        parts.append(self._nav("/"))
        if flash in FLASH_KEYS:
            parts.append(f"<p class='flash'>{html.escape(t['flash_' + flash])}</p>")
        parts.append(self.setup_hint())
        parts.append(self.current_block())
        if is_sample:
            parts.append(f"<p class='note'>{html.escape(t['sample_note'])}</p>")
            parts.append(f"<p class='note'>{html.escape(t['never_updated'])}</p>")
        else:
            stamp = data.fetched_at.strftime(TEXT[language]["date_format"] + " %H:%M")
            parts.append(f"<p class='note'>{html.escape(t['last_updated'].format(time=stamp))}</p>")
        now = self.now()
        quiet_end = quiet_hours_end(now, settings.display_quiet_hours)
        if quiet_end is not None:
            quiet = t["quiet_until"].format(time=quiet_end.strftime("%H:%M"))
            parts.append(f"<p class='note'>{html.escape(quiet)}</p>")
        state_dir = self.state_dir
        status = load_status(state_dir, zone(settings.studylife_timezone))
        error = status.last_error
        if error is not None:
            when = error.at.strftime(TEXT[language]["date_format"] + " %H:%M")
            line = t["last_error"].format(time=when, message=error.message)
            parts.append(f"<p class='flash'>{html.escape(line)}</p>")
        if not status.sessions_ok:
            note = t["sessions_failed"].format(message=status.sessions_error or "?")
            parts.append(f"<p class='warn'>{html.escape(note)}</p>")

        parts.append("<form method='post' action='/layout'><div class='grid'>")
        cards: list[tuple[str, str, str]] = [
            (
                AUTO,
                t["auto_name"]
                + " · "
                + t["auto_now"].format(layout=LAYOUTS[resolved].name[language]),
                t["auto_description"],
            )
        ]
        cards += [
            (spec.key, spec.name[language], spec.description[language]) for spec in LAYOUTS.values()
        ]
        for key, name, description in cards:
            checked = " checked" if key == choice else ""
            parts.append(
                "<label class='card'>"
                f"<input type='radio' name='layout' value='{key}'{checked}> "
                f"<b>{html.escape(name)}</b><small>{html.escape(description)}</small>"
                f"<img src='/preview/{key}.png' width='800' height='480' loading='lazy' "
                f"alt='{html.escape(name)}'>"
                "</label>"
            )
        parts.append("</div><div class='actions'>")
        parts.append(f"<button class='primary' type='submit'>{html.escape(t['apply'])}</button>")
        parts.append("</div></form>")
        parts.append(
            "<form method='post' action='/refresh' class='actions' style='margin-top:12px'>"
            f"<button type='submit'>{html.escape(t['refresh'])}</button></form>"
        )
        rules = t["auto_rules"].format(
            days=EXAM_SOON_DAYS,
            review=settings.display_auto_review or t["auto_off"],
            agenda=settings.display_auto_agenda or t["auto_off"],
        )
        parts.append(f"<p class='note'>{html.escape(rules)}</p>")
        parts.append(f"<p class='note'>{html.escape(t['full_refresh_note'])}</p>")
        parts.append(f"<footer>{html.escape(self.footer_line(state_dir, now))}</footer>")
        return _page(t["title"], "".join(parts))

    def connect_page(self, flash: str | None = None) -> bytes:
        t = self.text
        mode, redirect_uri = self.connect_mode()
        instance = str(self.settings.studylife_base_url).rstrip("/")
        parts = [f"<h1>{html.escape(t['title'])} · {html.escape(t['connect_heading'])}</h1>"]
        parts.append(self._nav("/connect"))
        if flash in CONNECT_FLASH_KEYS:
            message = t["connect_flash_" + flash].format(detail=self._flash_detail)
            parts.append(f"<p class='flash'>{html.escape(message)}</p>")
        parts.append(f"<p class='flash'>{html.escape(self.identity_line())}</p>")
        if root_is_overlay():
            parts.append(
                f"<p class='warn'>{html.escape(t['connect_overlay'])} "
                f"<a href='{README_OVERLAY_URL}'>README</a></p>"
            )
        intro = t["connect_intro"].format(
            instance=instance,
            client=CLIENT_ID,
            scopes=", ".join(SCOPES),
            redirect_uri=redirect_uri,
        )
        parts.append(f"<p class='note'>{html.escape(intro)}</p>")

        pending = self.pending()
        if pending is None:
            parts.append(
                "<form method='post' action='/connect/start' class='actions'>"
                f"<button class='primary' type='submit'>{html.escape(t['connect_start'])}</button>"
                "</form>"
            )
        else:
            parts.append(f"<p>{html.escape(t['connect_step_open'])}</p>")
            parts.append(
                f"<pre class='link'><a href='{html.escape(pending.connect_url, quote=True)}' "
                f"target='_blank' rel='noopener'>{html.escape(pending.connect_url)}</a></pre>"
            )
            valid = t["connect_valid_until"].format(time=pending.expires_at.strftime("%H:%M"))
            parts.append(f"<p class='note'>{html.escape(valid)}</p>")
            if mode == "paste":
                step = t["connect_step_paste"].format(redirect_uri=redirect_uri)
                parts.append(f"<p>{html.escape(step)}</p>")
                parts.append(
                    "<form method='post' action='/connect/paste' class='field'>"
                    f"<label for='callback_url'>{html.escape(t['connect_paste_label'])}</label>"
                    "<textarea id='callback_url' name='callback_url' required "
                    "autocomplete='off' spellcheck='false'></textarea>"
                    f"<button class='primary' type='submit'>"
                    f"{html.escape(t['connect_paste_button'])}</button></form>"
                )
            else:
                step = t["connect_step_redirect"].format(redirect_uri=redirect_uri)
                parts.append(f"<p>{html.escape(step)}</p>")
            parts.append(
                "<form method='post' action='/connect/start' class='actions'>"
                f"<button type='submit'>{html.escape(t['connect_restart'])}</button></form>"
            )
        parts.append(
            f"<footer>{html.escape(self.footer_line(self.state_dir, self.now()))}</footer>"
        )
        return _page(t["title"], "".join(parts))

    def settings_page(
        self,
        flash: str | None = None,
        submitted: dict[str, Any] | None = None,
        errors: dict[str, str] | None = None,
    ) -> bytes:
        t = self.text
        settings = self.effective()
        sources = override_sources(self.settings)
        errors = errors or {}
        values: dict[str, Any] = {
            "language": settings.display_language,
            "rotate": settings.display_rotate,
            "quiet_hours": settings.display_quiet_hours,
            "clear_at": settings.display_clear_at,
            "update_check": settings.display_update_check,
            "auto_review": settings.display_auto_review,
            "auto_agenda": settings.display_auto_agenda,
        }
        if submitted:
            values.update(submitted)

        def source(key: str) -> str:
            label = t["settings_source_file"] if sources.get(key) else t["settings_source_env"]
            return f"<span class='source'>{html.escape(label)}</span>"

        def error(key: str) -> str:
            return (
                f"<small class='error'>{html.escape(errors[key])}</small>" if key in errors else ""
            )

        parts = [f"<h1>{html.escape(t['title'])} · {html.escape(t['settings_heading'])}</h1>"]
        parts.append(self._nav("/settings"))
        if flash in SETTINGS_FLASH_KEYS:
            parts.append(f"<p class='flash'>{html.escape(t['settings_flash_' + flash])}</p>")
        if errors:
            parts.append(f"<p class='flash'>{html.escape(t['settings_invalid'])}</p>")
        parts.append(f"<p class='note'>{html.escape(t['settings_intro'])}</p>")
        parts.append("<form method='post' action='/settings' class='field'>")

        parts.append(
            f"<label for='language'>{html.escape(t['settings_language'])}"
            f"{source('language')}</label>"
        )
        parts.append("<select id='language' name='language'>")
        for code in LANGUAGES:
            selected = " selected" if values["language"] == code else ""
            parts.append(f"<option value='{code}'{selected}>{code}</option>")
        parts.append("</select>" + error("language"))

        parts.append(
            f"<label for='rotate'>{html.escape(t['settings_rotate'])}{source('rotate')}</label>"
        )
        parts.append("<select id='rotate' name='rotate'>")
        for rotation in ROTATIONS:
            selected = " selected" if str(values["rotate"]) == str(rotation) else ""
            label = t[f"settings_rotate_{rotation}"]
            parts.append(f"<option value='{rotation}'{selected}>{html.escape(label)}</option>")
        parts.append("</select>" + error("rotate"))

        parts.append(
            f"<label for='quiet_hours'>{html.escape(t['settings_quiet_hours'])}"
            f"{source('quiet_hours')}</label>"
            f"<input id='quiet_hours' name='quiet_hours' type='text' "
            f"value='{html.escape(str(values['quiet_hours']), quote=True)}'>"
            f"{error('quiet_hours')}<small>{html.escape(t['settings_quiet_hours_hint'])}</small>"
        )
        parts.append(
            f"<label for='clear_at'>{html.escape(t['settings_clear_at'])}"
            f"{source('clear_at')}</label>"
            f"<input id='clear_at' name='clear_at' type='text' "
            f"value='{html.escape(str(values['clear_at']), quote=True)}'>"
            f"{error('clear_at')}<small>{html.escape(t['settings_clear_at_hint'])}</small>"
        )
        for key in ("auto_review", "auto_agenda"):
            parts.append(
                f"<label for='{key}'>{html.escape(t['settings_' + key])}{source(key)}</label>"
                f"<input id='{key}' name='{key}' type='text' "
                f"value='{html.escape(str(values[key]), quote=True)}'>"
                f"{error(key)}<small>{html.escape(t['settings_' + key + '_hint'])}</small>"
            )
        checked = " checked" if values["update_check"] else ""
        parts.append(
            f"<label><input type='checkbox' name='update_check'{checked}> "
            f"{html.escape(t['settings_update_check'])}{source('update_check')}</label>"
            f"{error('update_check')}"
        )
        parts.append(
            "<div class='actions' style='margin-top:12px'>"
            f"<button class='primary' type='submit'>{html.escape(t['settings_save'])}</button>"
            "</div></form>"
        )
        parts.append(
            "<form method='post' action='/settings/reset' class='actions' style='margin-top:12px'>"
            f"<button type='submit'>{html.escape(t['settings_reset'])}</button></form>"
        )

        parts.append(f"<h2>{html.escape(t['settings_readonly_heading'])}</h2>")
        parts.append(f"<p class='note'>{html.escape(t['settings_readonly_note'])}</p>")
        parts.append("<table>")
        interval = t["settings_interval_value"].format(unit=TIMER_UNIT)
        parts.append(
            f"<tr><th>{html.escape(t['settings_interval'])}</th><td>{html.escape(interval)}</td>"
            f"<td>{html.escape(TIMER_UNIT)}</td></tr>"
        )
        for name, field, show_value in READONLY_FIELDS:
            raw = getattr(self.settings, field)
            presence = t["settings_set"] if raw else t["settings_unset"]
            shown = str(raw) if show_value else presence
            parts.append(
                f"<tr><th>{html.escape(name)}</th><td class='mono'>{html.escape(shown)}</td>"
                f"<td>{html.escape(t['settings_env_source'])}</td></tr>"
            )
        parts.append("</table>")
        parts.append(
            f"<footer>{html.escape(self.footer_line(self.state_dir, self.now()))}</footer>"
        )
        return _page(t["title"], "".join(parts))

    def footer_line(self, state_dir: Path, now: datetime) -> str:
        """ "Version 1.2.0", plus "Update available: v1.3.0" when the update check is on
        and GitHub (asked at most once per six hours, failures silent) knows a newer tag."""
        settings = self.effective()
        running = package_version()
        line = self.text["version"].format(version=running)
        if not settings.display_update_check:
            return line
        tz = zone(settings.studylife_timezone)
        latest = latest_release(state_dir, now, tz, fetch_latest_tag)
        if latest is not None and is_newer(latest, running):
            line += TEXT[self.language]["separator"]
            line += self.text["update_available"].format(tag=latest)
        return line

    def simple_page(self, message: str) -> bytes:
        return _page(self.text["title"], f"<p class='flash'>{html.escape(message)}</p>")


class DisplayServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def __init__(self, address: tuple[str, int], app: WebApp) -> None:
        super().__init__(address, RequestHandler)
        self.app = app


class RequestHandler(BaseHTTPRequestHandler):
    server: DisplayServer
    protocol_version = "HTTP/1.1"

    @property
    def app(self) -> WebApp:
        return self.server.app

    # One line per request on stderr through the logger; the request line carries method
    # and path only, never the body (where the token travels) or the cookie header. The
    # callback's query (the assertion) is cut off too.
    def log_message(self, format: str, *args: object) -> None:
        line = format % args
        if "/connect/callback?" in line:
            line = line.split("?", 1)[0] + "?..."
        log.info("%s %s", self.address_string(), line)

    # -- helpers ------------------------------------------------------------------------

    def _send(
        self,
        status: HTTPStatus,
        body: bytes,
        content_type: str = "text/html; charset=utf-8",
        extra_headers: list[tuple[str, str]] | None = None,
    ) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "same-origin")
        for name, value in extra_headers or []:
            self.send_header(name, value)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _redirect(self, location: str, extra_headers: list[tuple[str, str]] | None = None) -> None:
        self.send_response(HTTPStatus.SEE_OTHER)
        self.send_header("Location", location)
        self.send_header("Content-Length", "0")
        self.send_header("Cache-Control", "no-store")
        for name, value in extra_headers or []:
            self.send_header(name, value)
        self.end_headers()

    def _authenticated(self) -> bool:
        return self.app.is_authenticated(self.headers.get("Cookie"))

    def _same_origin(self) -> bool:
        """Browsers send Sec-Fetch-Site on every request and Origin on form POSTs; either
        one has to say "same origin". A request with neither is not a browser form
        submission and is refused."""
        fetch_site = self.headers.get("Sec-Fetch-Site")
        if fetch_site is not None:
            return fetch_site in ("same-origin", "none")
        origin = self.headers.get("Origin")
        host = self.headers.get("Host")
        if origin is None or host is None:
            return False
        return origin.rstrip("/") == f"http://{host}"

    def _form(self) -> dict[str, str]:
        """Reads and parses the whole body first, whatever the route decides afterwards: an
        unread body on a keep-alive connection would be parsed as the next request line."""
        length = int(self.headers.get("Content-Length") or 0)
        if length < 0 or length > MAX_BODY_BYTES:
            self.close_connection = True
            return {}
        raw = self.rfile.read(length).decode("utf-8", errors="replace")
        return {key: values[0] for key, values in parse_qs(raw).items() if values}

    def _run_refresh(self) -> str:
        """Runs the pipeline and maps its outcome onto a flash key."""
        try:
            outcome = self.app.refresh()
        except Exception:
            log.exception("refresh from the web interface failed")
            return "failed"
        return "refreshed" if outcome == 0 else "failed"

    def _flash(self, query: str) -> str | None:
        return parse_qs(query).get("m", [None])[0]

    # -- routes -------------------------------------------------------------------------

    def do_GET(self) -> None:
        parts = urlsplit(self.path)
        app = self.app
        if parts.path == "/healthz":
            # For an uptime monitor: no cookie, no origin check, nothing secret inside.
            tz = zone(app.settings.studylife_timezone)
            report, status = health_report(app.settings, datetime.now(tz))
            body = json.dumps(report).encode("utf-8")
            self._send(status, body, content_type="application/json")
            return
        if parts.path == "/connect/callback":
            # StudyLife's redirect: no cookie (SameSite=Strict never travels cross-site),
            # the single-use state is the binding. The outcome page names it either way.
            outcome = app.finish_connect(parts.query)
            text = app.text
            if outcome == "applied":
                self._send(HTTPStatus.OK, app.simple_page(text["connect_callback_done"]))
                return
            message = text["connect_flash_" + outcome].format(detail=app._flash_detail)
            self._send(HTTPStatus.BAD_REQUEST, app.simple_page(message))
            return
        if parts.path == "/":
            if not self._authenticated():
                self._send(HTTPStatus.OK, app.login_page())
                return
            self._send(HTTPStatus.OK, app.layouts_page(self._flash(parts.query)))
            return
        if parts.path in ("/connect", "/settings"):
            if not self._authenticated():
                self._send(HTTPStatus.FORBIDDEN, app.simple_page(app.text["forbidden"]))
                return
            page = app.connect_page if parts.path == "/connect" else app.settings_page
            self._send(HTTPStatus.OK, page(self._flash(parts.query)))
            return
        if parts.path == "/current.png":
            if not self._authenticated():
                self._send(HTTPStatus.FORBIDDEN, app.simple_page(app.text["forbidden"]))
                return
            png = app.current_png()
            if png is None:
                self._send(HTTPStatus.NOT_FOUND, app.simple_page(app.text["not_found"]))
                return
            self._send(HTTPStatus.OK, png, content_type="image/png")
            return
        if parts.path.startswith("/preview/") and parts.path.endswith(".png"):
            if not self._authenticated():
                self._send(HTTPStatus.FORBIDDEN, app.simple_page(app.text["forbidden"]))
                return
            key = parts.path[len("/preview/") : -len(".png")]
            if not is_valid_choice(key):
                self._send(HTTPStatus.NOT_FOUND, app.simple_page(app.text["not_found"]))
                return
            self._send(HTTPStatus.OK, app.preview_png(key), content_type="image/png")
            return
        self._send(HTTPStatus.NOT_FOUND, app.simple_page(app.text["not_found"]))

    def do_HEAD(self) -> None:
        self.do_GET()

    def do_POST(self) -> None:
        parts = urlsplit(self.path)
        app = self.app
        form = self._form()
        if parts.path == "/login":
            token = form.get("token", "")
            if not app.token_matches(token):
                time.sleep(WRONG_TOKEN_DELAY_SECONDS)
                self._send(HTTPStatus.FORBIDDEN, app.login_page(app.text["wrong_token"]))
                return
            cookie = (
                f"{SESSION_COOKIE}={app.session_cookie_value()}; HttpOnly; SameSite=Strict; Path=/"
            )
            self._redirect("/", [("Set-Cookie", cookie)])
            return
        if parts.path == "/logout":
            expired = f"{SESSION_COOKIE}=; Max-Age=0; HttpOnly; SameSite=Strict; Path=/"
            self._redirect("/", [("Set-Cookie", expired)])
            return
        protected = {
            "/layout",
            "/refresh",
            "/connect/start",
            "/connect/paste",
            "/settings",
            "/settings/reset",
        }
        if parts.path not in protected:
            self._send(HTTPStatus.NOT_FOUND, app.simple_page(app.text["not_found"]))
            return
        if not self._authenticated() or not self._same_origin():
            self._send(HTTPStatus.FORBIDDEN, app.simple_page(app.text["forbidden"]))
            return
        if parts.path == "/layout":
            choice = form.get("layout", "")
            if not is_valid_choice(choice):
                self._send(HTTPStatus.BAD_REQUEST, app.simple_page(app.text["bad_request"]))
                return
            save_layout_choice(app.settings, choice)
            log.info("layout choice set to %s", choice)
            outcome = self._run_refresh()
            self._redirect("/?m=" + ("saved" if outcome == "refreshed" else outcome))
            return
        if parts.path == "/refresh":
            self._redirect("/?m=" + self._run_refresh())
            return
        if parts.path == "/connect/start":
            app.begin_connect()
            self._redirect("/connect?m=started")
            return
        if parts.path == "/connect/paste":
            self._redirect("/connect?m=" + app.finish_connect(form.get("callback_url", "")))
            return
        if parts.path == "/settings/reset":
            update_overrides(
                app.settings,
                language=None,
                rotate=None,
                quiet_hours=None,
                clear_at=None,
                update_check=None,
                auto_review=None,
                auto_agenda=None,
            )
            log.info("web settings reset to the environment values")
            self._redirect("/settings?m=reset")
            return
        values, errors = app.parse_settings_form(form)
        if errors:
            self._send(HTTPStatus.BAD_REQUEST, app.settings_page(None, values, errors))
            return
        update_overrides(app.settings, **values)
        log.info("web settings saved: %s", values)
        self._redirect("/settings?m=saved")


# Where deploy/install.sh generates the self-signed certificate DISPLAY_TLS=true serves.
# Fixed, not configurable: one well-known pair the install script, this module and the
# systemd units' file permissions all agree on, the same way ENV_FILE is fixed elsewhere.
TLS_CERT_PATH = "/etc/studylife-display-tls.pem"
TLS_KEY_PATH = "/etc/studylife-display-tls.key"


def make_server(
    settings: Settings, refresh: Callable[[], int], bind: str | None = None
) -> DisplayServer:
    """Binds (but does not serve); tests pass "127.0.0.1:0" and read `server_address`."""
    server = DisplayServer(parse_bind(bind or settings.display_web_bind), WebApp(settings, refresh))
    if settings.display_tls:
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.minimum_version = ssl.TLSVersion.TLSv1_2
        ctx.load_cert_chain(TLS_CERT_PATH, TLS_KEY_PATH)
        server.socket = ctx.wrap_socket(server.socket, server_side=True)
    return server


def serve_web(settings: Settings, refresh: Callable[[], int]) -> int:
    server = make_server(settings, refresh)
    host, port = server.server_address[0], server.server_address[1]
    log.info(
        "web interface listening on %s://%s:%d/ (layouts: %s)",
        "https" if settings.display_tls else "http",
        host,
        port,
        ", ".join(sorted(valid_choices())),
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0
